apiVersion: v1
kind: Secret
metadata:
  name: tomcat-secret
  namespace: project
stringData:
  DB_URL: "jdbc:mysql://[mysql-master VM IP]:3306,[mysql-slave VM IP]:3307/car"
  DB_USER: "[db_user]"
  DB_PASSWORD: "[db_password]"
