apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-login
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login
      rel: stable
  template:
    metadata:
      labels:
        app: login
        rel: stable
    spec:
      containers:
      - name: tomcat
        image: jojeongseok/login:v1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-login
spec:
  clusterIP: 10.100.100.100
  selector:
    app: login
    rel: stable
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
