apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
      rel: stable
  template:
    metadata:
      labels:
        app: order
        rel: stable
    spec:
      containers:
      - name: tomcat
        image: jojeongseok/order:v1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-order
spec:
  clusterIP: 10.100.100.102
  selector:
    app: order
    rel: stable
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
