apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-reserve
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reserve
      rel: stable
  template:
    metadata:
      labels:
        app: reserve
        rel: stable
    spec:
      containers:
      - name: tomcat
        image: jojeongseok/reserve:v1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-reserve
spec:
  clusterIP: 10.100.100.104
  selector:
    app: reserve
    rel: stable
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
