apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-board
spec:
  replicas: 1
  selector:
    matchLabels:
      app: board
      rel: stable
  template:
    metadata:
      labels:
        app: board
        rel: stable
    spec:
      containers:
      - name: tomcat
        image: jojeongseok/board:v1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-board
spec:
  clusterIP: 10.100.100.103
  selector:
    app: board
    rel: stable
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

